### ISSUE TITLE
Backtest Error: order/order.py : new_price=self.update_data["new_price"] : KeyError: 'new_price'

### ISSUE THREAD

**Issue by andrewl36** [liampauling/flumine#548]
Periodically seeing this error, following a "market.replace_order(order, price)"
```
Traceback (most recent call last):
  File "backdog.py", line 50, in <module>
    framework.run()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/backtest/backtest.py", line 97, in run
    self._process_market_books(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/backtest/backtest.py", line 117, in _process_market_books
    self._check_pending_packages(market_id)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/backtest/backtest.py", line 186, in _check_pending_packages
    order_package.client.execution.handler(order_package)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/execution/simulatedexecution.py", line 31, in handler
    func(order_package, http_session=None)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/execution/simulatedexecution.py", line 117, in execute_replace
    order_package, order_package.replace_instructions
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/order/orderpackage.py", line 160, in replace_instructions
    return [order.create_replace_instruction() for order in self]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/order/orderpackage.py", line 160, in <listcomp>
    return [order.create_replace_instruction() for order in self]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flumine/order/order.py", line 404, in create_replace_instruction
    bet_id=self.bet_id, new_price=self.update_data["new_price"]
KeyError: 'new_price'

```

**Comment by andrewl36** [comment]
I have a suspicion in at least one occurence of this, the order being replaced at a new price of 4.9, got matched at exactly the same time from the previous order that was being replaced:
```
{"asctime": "2022-01-09 00:26:13,581", "levelname": "WARNING", "message": "Order at : 380 : BACK 22802414 : PRICE=4.8 : STAKE=5.26"}
{"asctime": "2022-01-09 00:26:13,611", "levelname": "WARNING", "message": "unmatched : PRICE not moved: 343 1.184155151:22802414 PRICE = 4.8"}
{"asctime": "2022-01-09 00:26:13,646", "levelname": "WARNING", "message": "unmatched : REPLACED BACK order at: 307 1.184155151:22802414 new PRICE = 5.0"}
{"asctime": "2022-01-09 00:26:13,647", "levelname": "WARNING", "message": "ORDER_CANCEL: 307 1.184155151:22802414 size_matched = 0.56 size_cancelled = 4.7 size_remaining = 0.0 price = 4.8"}
{"asctime": "2022-01-09 00:26:13,690", "levelname": "WARNING", "message": "unmatched : REPLACED BACK order at: 270 1.184155151:22802414 new PRICE = 4.9"}
{"asctime": "2022-01-09 00:26:13,690", "levelname": "WARNING", "message": "ORDER_COMPLETE: 270 1.184155151:22802414 size_matched = 4.7 size_cancelled = 0.0 size_remaining = 0.0 avg_price_matched = 5.0"}
```

**Comment by andrewl36** [comment]
@liampauling this PR fixes the problem, although maybe not elegant as I do not fully understanding the simulation, so i'll let you review... https://github.com/liampauling/flumine/pull/549

**Comment by andrewl36** [comment]
thank you @liampauling
